const data = [
  {
    debtId: '14317047',
    addressCounty: '',
    caseId: '3213',
    currentBalance: 10130,
    fileId: '4642049',
    lawFirmId: null,
    originalCreditor: 'American Express',
    plaintiffId: null,
    masterDebtId: '14878446',
    legalFileId: '',
    firstName: 'Alexander',
    lastName: 'Fitzgerald',
    coApplicantFirstName: 'Arthur',
    coApplicantLastName: 'Parks',
    assignedAttorney: 'John Doe',
    state: 'TX',
  },
  {
    debtId: '14317044',
    addressCounty: '',
    caseId: '5466 2640 0564 1483',
    currentBalance: 12323,
    fileId: '4642049',
    lawFirmId: null,
    originalCreditor: 'CHASE CARD',
    plaintiffId: null,
    masterDebtId: '14317044',
    legalFileId: '',
    firstName: 'Alexander',
    lastName: 'Fitzgerald',
    coApplicantFirstName: 'Arthur',
    coApplicantLastName: 'Parks',
    assignedAttorney: 'John Doe',
    state: 'TX',
  },
  {
    debtId: '14317042',
    addressCounty: 'Hello',
    caseId: '3213',
    currentBalance: 3,
    fileId: '4642049',
    lawFirmId: null,
    originalCreditor: 'American Express',
    plaintiffId: null,
    legalFileId: '556675',
    masterDebtId: '14878446',
    firstName: 'Alexander',
    lastName: 'Fitzgerald',
    coApplicantFirstName: 'Arthur',
    coApplicantLastName: 'Parks',
    assignedAttorney: 'John Doe',
    state: 'TX',

  },  {
    debtId: '14317041',
    addressCounty: '',
    caseId: 'Case No. 2019CV05734',
    currentBalance: 16611,
    fileId: '4642049',
    lawFirmId: null,
    originalCreditor: 'Bank of America',
    plaintiffId: null,
    legalFileId: '',
    firstName: 'Alexander',
    lastName: 'Fitzgerald',
    coApplicantFirstName: 'Arthur',
    coApplicantLastName: 'Parks',
    assignedAttorney: 'John Doe',
    state: 'TX',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14860077',
    fileId: '13933782',
    caseId: '681482867',
    originalCreditor: 'CAPITAL ONE',
    currentBalance: 11657.71,
    plaintiffId: null,
    lawFirmId: null,
    masterDebtId: '13832919',
    firstName: 'Mabelle',
    lastName: 'Armstrong',
    coApplicantFirstName: null,
    coApplicantLastName: null,
    assignedAttorney: 'John Doe',
    state: 'TX',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14949313',
    fileId: '13935081',
    caseId: '681482867',
    originalCreditor: 'American Express',
    currentBalance: 11541.1,
    plaintiffId: null,
    lawFirmId: null,
    masterDebtId: '13832919',
    firstName: 'Mabelle',
    lastName: 'Ross',
    coApplicantFirstName: null,
    coApplicantLastName: null,
    assignedAttorney: 'John Doe',
    state: 'OH',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14949311',
    fileId: '13935081',
    caseId: '3213',
    originalCreditor: 'Discover Bank',
    currentBalance: 52,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    masterDebtId: '14878446',
    firstName: 'Mabelle',
    lastName: 'Ross',
    coApplicantFirstName: null,
    coApplicantLastName: null,
    assignedAttorney: 'John Doe',
    state: 'OH',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '13832924',
    fileId: 'CS4496',
    caseId: '681482867',
    originalCreditor: 'Barclays Bank',
    currentBalance: 2,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    masterDebtId: '13832919',
    firstName: 'Charles',
    lastName: 'Guerrini',
    coApplicantFirstName: null,
    coApplicantLastName: null,
    assignedAttorney: 'John Doe',
    state: 'UT',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '13832922',
    fileId: 'CS4496',
    caseId: '5178057981132363',
    originalCreditor: 'Capital One',
    currentBalance: 5000,
    plaintiffId: null,
    lawFirmId: null,
    firstName: 'Charles',
    lastName: 'Guerrini',
    coApplicantFirstName: null,
    coApplicantLastName: null,
    assignedAttorney: 'John Doe',
    state: 'UT',

  },
  {    debtId: '13832920',
    fileId: 'CS4496',
    caseId: '3213',
    originalCreditor: 'Sears/Citibank',
    currentBalance: 4,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    masterDebtId: '14878446',
    firstName: 'Charles',
    lastName: 'Guerrini',
    coApplicantFirstName: null,
    coApplicantLastName: null,
    assignedAttorney: 'John Doe',
    state: 'UT',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '13832919',
    fileId: 'CS4496',
    caseId: '681482867',
    originalCreditor: 'Citibank',
    currentBalance: 121,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    masterDebtId: '13832919',
    firstName: 'Charles',
    lastName: 'Guerrini',
    coApplicantFirstName: null,
    coApplicantLastName: null,
    assignedAttorney: 'John Doe',
    state: 'UT',

  },
  {
    debtId: '14736219',    fileId: '13931794',
    caseId: '321333333333333333',
    originalCreditor: 'Comenity Capital Bank/Overstock',
    currentBalance: 15,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    firstName: 'Theresa',
    lastName: 'Matteucci',
    coApplicantFirstName: 'Bill',
    coApplicantLastName: 'Fossi',
    assignedAttorney: 'John Doe',
    state: 'CA',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14736218',
    fileId: '13931794',
    caseId: '5206 0208 0589 1234',
    originalCreditor: 'CAPITAL ONE',
    currentBalance: 123456,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    firstName: 'Theresa',
    lastName: 'Matteucci',
    coApplicantFirstName: 'Bill',
    coApplicantLastName: 'Fossi',
    assignedAttorney: 'John Doe',
    state: 'CA',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14736216',
    fileId: '13931794',
    caseId: '007 440 183 60001',
    originalCreditor: 'Citibank/Shell',
    currentBalance: 583,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    firstName: 'Theresa',
    lastName: 'Matteucci',
    coApplicantFirstName: 'Bill',
    coApplicantLastName: 'Fossi',
    assignedAttorney: 'John Doe',
    state: 'CA',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14736214',
    fileId: '13931794',
    caseId: '3213',
    originalCreditor: 'SYNCB/PPXTRM',
    currentBalance: 42521,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    masterDebtId: '14878446',
    firstName: 'Theresa',
    lastName: 'Matteucci',
    coApplicantFirstName: 'Bill',
    coApplicantLastName: 'Fossi',
    assignedAttorney: 'John Doe',
    state: 'CA',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14736213',
    fileId: '13931794',
    caseId: '3213',
    originalCreditor: 'Comenity Bank/Samuels',
    currentBalance: 763,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    masterDebtId: '14878446',
    firstName: 'Theresa',
    lastName: 'Matteucci',
    coApplicantFirstName: 'Bill',
    coApplicantLastName: 'Fossi',
    assignedAttorney: 'John Doe',
    state: 'CA',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14736211',
    fileId: '13931794',
    caseId: '302279223',
    originalCreditor: 'CREDITONEBNK',
    currentBalance: 13610,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    firstName: 'Theresa',
    lastName: 'Matteucci',
    coApplicantFirstName: 'Bill',
    coApplicantLastName: 'Fossi',
    assignedAttorney: 'John Doe',
    state: 'CA',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14736210',
    fileId: '13931794',
    caseId: '27190428',
    originalCreditor: 'Citibank',
    currentBalance: 979,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    firstName: 'Theresa',
    lastName: 'Matteucci',
    coApplicantFirstName: 'Bill',
    coApplicantLastName: 'Fossi',
    assignedAttorney: 'John Doe',
    state: 'CA',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14736209',
    fileId: '13931794',
    caseId: '5463 2576 7871 6981',
    originalCreditor: 'CAP1/CABEL',
    currentBalance: 1235.27,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    firstName: 'Theresa',
    lastName: 'Matteucci',
    coApplicantFirstName: 'Bill',
    coApplicantLastName: 'Fossi',
    assignedAttorney: 'John Doe',
    state: 'CA',
    legalStatusTypes: [],
    statuses: []
  },
  {
    debtId: '14736208',
    fileId: '13931794',
    caseId: '19-65049',
    originalCreditor: 'SYNCB/JCP',
    currentBalance: 1014,
    plaintiffId: null,
    lawFirmId: null,
    addressCounty: '',
    legalFileId: '',
    firstName: 'Theresa',
    lastName: 'Matteucci',
    coApplicantFirstName: 'Bill',
    coApplicantLastName: 'Fossi',
    assignedAttorney: 'John Doe',
    state: 'CA',
    legalStatusTypes: [],
    statuses: []
  }
];

const filtered = data.filter(v => (v.debtId === v.masterDebtId || !v.masterDebtId));
console.log(data.length);
console.log(filtered.length);
